### ISSUE TITLE
[Request] Have title and episode name auto populate in video file.

### ISSUE THREAD

**Issue by Vigilence** [clienthax/Crunched#1]
So far the newest release works very well.  The only issue would be that the files produced are named a generic `Videos` for each file produced.  Example : `Videos - s01e01 - [CrunchyRoll].mkv`

If the shows name can be auto added, or manually that would be very useful.  I would ask a second request for episode name if that's even possible.

Example way of how I name my videos: ` Berserk 01 - The Dragon Slayer`
Another acceptable way` Beserk - S01E01 - The Dragon Slayer`
Third alternative `E01 - The Dragon Slayer`

**Comment by clienthax** [comment]
Its likely to be the 2nd option for compatibility with Plex, this is basically something I overlooked as Plex handles all the metadata for me :)

Il add an option in for it when I wake up

**Comment by clienthax** [comment]
Actually, what show are you attempting to download?, As the show name should already be in the name,

**Comment by Vigilence** [comment]
I downloaded Berserk Season 01 and 02.

![screenshot 40](https://user-images.githubusercontent.com/22781570/33349271-63d05a4c-d467-11e7-9cf8-d4171f8b219a.png)

**Comment by clienthax** [comment]
What is the exact page you are using?, It looks like you might have /videos on the end of something?
It works fine for me, https://i.imgur.com/xI3kcQV.png

**Comment by Vigilence** [comment]
Yeah, the url had videos at the end `http://www.crunchyroll.com/berserk/videos`

**Comment by clienthax** [comment]
Fixed the metadata title not being added,
Added option -addtitle to add the title to the filename

**Comment by Vigilence** [comment]
Works really well!  The episode name is added in perfectly.  I would change the the command to episode name since the title is automatically added by default.

![screenshot 41](https://user-images.githubusercontent.com/22781570/33398046-96d87992-d51b-11e7-9d05-8bd81e7602c7.png)
